application/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_uploads import UploadSet, IMAGES


images = UploadSet('images', IMAGES)


class UploadImage(FlaskForm):
  """Upload sound form."""
  image = FileField(validators=[
    FileAllowed(images, 'Image only!'), 
    FileRequired('File was empty!')])

application/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class
from .forms import images


def create_app():
    """Construct the core application."""
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.Config')
    Bootstrap(app)

    configure_uploads(app, images)
    patch_request_class(app)

    with app.app_context():
        # Imports
        from . import routes
        app.register_blueprint(routes.main_bp)

        # # Create tables for our models
        # db.create_all()

        return app

application/routes.py
from flask import current_app as app
from flask import Blueprint, render_template, request, redirect, url_for, flash, Markup, abort
from werkzeug.utils import secure_filename
from os import path
import uuid
from pathlib import Path
from .forms import UploadImage, images
from .seg_model import evaluate_image

from pathlib import PurePath

from PIL import Image


main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates')


@main_bp.route('/')
@main_bp.route('/index')
def index():
    return render_template('index.html')


@main_bp.route('/seg', methods=['GET', 'POST'])
def segmentation():
    form = UploadImage()
    in_url = None
    out_url = None
    if form.validate_on_submit():
        filename = uuid.uuid4().hex + '.jpg'
        path = app.config['UPLOADED_IMAGES_DEST']+'/'+filename
        image = request.files['image']
        with Image.open(image) as pil_image:
            old_size = pil_image.size
            if max(old_size) > 1000:
                pil_image = pil_image.resize(
                    (int(1000/max(old_size)*old_size[0]), int(1000/max(old_size)*old_size[1])))
            pil_image.save(path)
        in_url = images.url(filename)
        out_url = images.url(evaluate_image(path))
        return render_template('seg.html', form=form, in_url=in_url, out_url=out_url)
    return render_template('seg.html', form=form, in_url=in_url, out_url=out_url)

application/templates/index.html
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{{ super() }}
<div class="container-fluid">
  <div class="container text-center">
    <h1>Segmentation Demo for DLS</h1>
    <p>Enjoy!</p>
  </div>
</div>
{% endblock %}

application/templates/layout.html
{% extends "bootstrap/base.html" %}

{% block title %}Segmentation Demo{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{url_for('main_bp.index')}}">Main Page</a>
      <a class="navbar-brand" href="{{url_for('main_bp.segmentation')}}">Segmentation</a>
    </div>
  </div>
</nav>
{% endblock %}

application/templates/seg.html
{% extends 'layout.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{{ super() }}
<div class="container-fluid">
  <form class="form" method="post" role="form" enctype="multipart/form-data">
    {{ form.csrf_token() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    {{ wtf.form_field(form.image) }}
    <input class="btn btn-primary" type="submit" value="Upload">
  </form>
</div>
<hr>
{% if in_url and out_url %}
<div class="container-fluid row">
  <div class="col-md-6">
    <img class="img-responsive" src="{{ in_url }}">
  </div>
  <div class="col-md-6">
    <img class="img-responsive" src="{{ out_url }}">
  </div>
</div>
{% endif %}
{% endblock %}